# Generated by Django 5.0.9 on 2025-02-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codesitemainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField()),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tags', models.CharField(choices=[('csharp', 'C#'), ('react', 'React'), ('visual_studio', 'Visual Studio'), ('django', 'Django'), ('python', 'Python'), ('personal', 'Personal')], default='personal', max_length=20)),
            ],
        ),
    ]
